ALTER TABLE contact_us
ADD COLUMN created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP AFTER message,
ADD COLUMN updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
